### ISSUE TITLE
Recruitment filter system feedback access

### ISSUE THREAD

**Issue by toosyou** [purindaisuki/tkfmtools#11]
First of all, thanks for your great works!
It has saved us so much time recruiting.

Rumor has it that this repo is no longer updating, 
which makes me wonder is there any chance we can get access to the recruitment feedback form.
So that maybe the community can help to send charateric.json PR.

Also, it's very understandable if you're not planning to maintain this repo anymore.
Then I'll close this issue.

**Comment by purindaisuki** [comment]
I am kind of retired from the game now so there is no plan to update the the tool and the feedback form as well.
As far as I know people in tw cord created a thread to collect the recruitment tags. You may get the latest info there and are always welcome to open a PR. I will check it if I have time.

**Comment by toosyou** [comment]
Understood!
Thank you again for your dedication.
