### ISSUE TITLE
許願把篩選器改回前一版

### ISSUE THREAD

**Issue by not0000** [purindaisuki/tkfmtools#2]
前兩天改版的新ui，篩選器雖然有區隔了，但是手機上無法在一個畫面內看到所有篩選條件，需要上下拖曳才能選擇，使用上比較麻煩，希望能許願該回前一版 or 將行距改小一點

**Comment by purindaisuki** [comment]
感謝提醒，會把手機預設改回舊版並增加新舊版佈局切換按紐

**Comment by purindaisuki** [comment]
已新增功能
