### ISSUE TITLE
[ERROR]: GitHub Pages Issues

### ISSUE THREAD

**Issue by C0unt-zero** [purindaisuki/tkfmtools#28]
![purindaisuki github io_tkfmtools_ja_enlist_](https://user-images.githubusercontent.com/82859690/206899354-8fdb3954-b24a-4f63-8043-e89fda0fbce1.jpg)

![a](https://user-images.githubusercontent.com/82859690/206899314-e02c0ef7-8585-4a54-9f47-ea9b0ee9bba2.jpg)

The image is not loading and I am getting a 404 error.
It is trying to load from /static instead of from /tkfmtools/static due to a broken pathPrefix.
After gatsby clean, deploy again may solve the problem.

https://purindaisuki.github.io/static/9af8d94a3d65b6544798008d670f5047/e9a79/char_small_139.png
https://purindaisuki.github.io/tkfmtools/static/9af8d94a3d65b6544798008d670f5047/e9a79/char_small_139.png

https://c0unt-zero.github.io/tkfmtools/enlist/
The build may have been broken due to some effect, as I have not experienced any problems on my page.

**Comment by purindaisuki** [comment]
Should be fixed. Thanks :)
