### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by 10duckman** [purindaisuki/tkfmtools#3]
Hello, i'm korean gamer.
I'm interested your project. Can i fork your project for translate korean and some work?

regards.

**Comment by purindaisuki** [comment]
Hi,

Of course! The project is under MIT license but you should be aware of some
resources are not.

As for the translation, l am planning to add Japanese and Korean version in
recent days but feel free to fork the project or even create a PR, you are
totally welcome to do so.

Best.

10duckman ***@***.***> 於 2021年3月30日 週二 下午1:32 寫道：
